//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_PF_JorgeIsaacLopezV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cancion()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int id_cancion { get; set; }
        public string codigo_cancion { get; set; }
        public int id_genero { get; set; }
        public string nombre_cancion { get; set; }
        public decimal precio { get; set; }
        public string artista { get; set; }
    
        public virtual GeneroMusical GeneroMusical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}
