//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_PF_JorgeIsaacLopezV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int id_usuario { get; set; }
        public string numero_identificacion { get; set; }
        public string nombre_completo { get; set; }
        public string genero { get; set; }
        public string correo { get; set; }
        public int id_tipo_tarjeta { get; set; }
        public string numero_tarjeta { get; set; }
        public string contrasena { get; set; }
        public int id_perfil { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
