//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_PF_JorgeIsaacLopezV
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DetalleFactura
    {
        public string numero_factura { get; set; }
        public string Cliente { get; set; }
        public string nombre_cancion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal subtotal { get; set; }
        public decimal SubtotalFactura { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public Nullable<System.DateTime> fecha_compra { get; set; }
    }
}
